var fadeInDelay = 1500;
var fadeOutDelay = 1500;
var readingDelay = 6000;
var reviews = [
    { review_owner:'Erdinç Aybatar', txt:'Sayın Afgan Hocam, Photoshopu bana sevdirdiğiniz için çok teşekkür ederim. Gerçekten eğitim verme konusunda çok başarılısınız. Sizden bir ricam daha var, bizim için web site tasarımı içinde kapsamlı bir eğitim verir misiniz? Çok Teşekkür ederim.Ekleme: Sayın Afgan hocama ne kadar soru sorduysam, sorularımın hepsine cevapladı, hatta videolu cevap bile gönderdi. Kendisini şiddetle tavsiye ederim bu kursu kaçırmayın. Tekrar teşekkür ederim hocam.'},
    { review_owner:'Alparslan özhan', txt:'Oldukça detaylı ve öğretici bir kurs emekleriniz için teşekkürler .Kurs içeriği derli toplu ,alıştırmalarla öğrenilen hususların pekiştirilmesi sağlanmış. video sürelerini boğmayacak şekilde kısa tutmanız gerçekten her eğitmenin dikkat etmesi gereken bir husus. bunun için ayriyeten teşekkürler.'},
    { review_owner:'Murat Osmanağaoğlu', txt:'Afgan beyi youtobe kanalından zaten takip ediyorum. Ben bir fotoğrafçı değilim, web tasarımları yapıyorum, youtobe kanalındaki eğitimleri bana yetiyor ve artıyor, ancak bu kurs bana çok daha fazlasını kattı. Ellerine ve ağzına sağlık.'},
    { review_owner:'Şamil Yeşil', txt:'Fotoğraf çekmeyi çok seven bir insanım ama makinem olmadığı için telefonla çekmek zorunda kalıyorum. Etrafımdaki insanlar bana hep kendini dahada geliştir sende yetenek var derlerdi. Bir gün youtube da afgan abiye denk geldim ve Ps öğrenmeye karar verdim. Afgan abinin çok güzel bi konuşma biçimi var ve 12 yıllık eğitim hayatımda bana bu tarz bilgi öğretmeye çalışan öğretmenle karşılaşamadım. Ps ile kısıtlı kalmak istemedim Lr dersini de satın aldım. Güzel bir fotoğraf makinesi  alıp kendimi dahada geliştirmeye karar verdim. Afgan abimi burada sayfalarca anlatsam az kalır. Herkesin tanıması gereken bir insansın ve benim en iyi öğretmenimsin. Umarım hak ettiğin yerlere gelirsin abim. Kendine çok iyi bak.+ See more'},
    { review_owner:'Murat Yıldiz', txt:'dersler cok zevkli , programın yarısını gectim ve en cok öğrenmek istediğim panellerdeki secim araclarını daha etkili kullanmakti, hocamız cok sade ve anlasılır bir bizimde anlatıyor, kaynak dosyaları ile beraber hocamızla senkronize bir bicimde calısmaktayım. Saygılarımla'},
    { review_owner:'Hüseyin', txt:'Photoshop programını öğrenmeye yeni başladım, youtube den Afgan Rasulovun videolarını izledim ve gerçekten memnun kaldım. Photoshop programını iyi seviyede öğrenmek için udemy eğitim videosunu satın aldım herkese tavsiye ederim kursa gitmek yerine udemy ile her an elinizin altındaki videoları izleyip öğrenebilirsiniz. Herkesin emeğine sağlık diyorum.'},
    { review_owner:'Aykut İLTER', txt:'Bu kursun bana çok faydalı olacağına çok inanıyorum.Bu eğitimi de Afgan Rasulov eşliğinde ve temiz anlatımı sayesinde daha net anlayacağıma eminim.'},
    { review_owner:'Bahadır Dündar', txt:'Afgan bey gayet profesyonel ve konuya çok hakim bir eğitmen, tavsiye ederim.'},
    { review_owner:'Selma Aygörmez', txt:'Bu kursa katılmam ile birlikte fotoğraf düzenlemelerim ve kategorizasyonum level atladı ve kendime güvenim artmıştır . Afgan Rasulov Türkçeyi kullanımı ve açık anlatım tarzı ile photoshop derslerinde markadır'},
    { review_owner:'Faruk Dinc', txt:'Afgan Rasulov, profesyonel fotoğrafçı olduğu kadar Profesyonel de Eğitmen.. Daha önce bu kadar profesyonel hazırlanmış bir kurs ve anlatım görmedim..   Tek kelime ile Harika!'},
    { review_owner:'Ömer Yardımcı', txt:'Daha iyi olabilir ve daha fazla örnek olabilirdi. Yinede çok iyi anlatıyor yeni başlayanlar için ve en temel konuları öğrenmek isteyenler için iyi bir kaynak.'},
    { review_owner:'Ismail Can', txt:'evet doğru bir eşleşme.'},
    { review_owner:'Yaşar Bayındır', txt:'Gerçekten çok kaliteli bir eğitim.'},
    { review_owner:'Savaş Daniş', txt:'Mükemmel anlatım mükemmel kurs.'},
    { review_owner:'Enes sındıraç', txt:'Sağ olabi 2019 olmasada cs 6 da olan larla idare  ediyorum :)'},
    { review_owner:'Mehmet', txt:'Afgan hocam diksiyonu düzgün mikrofon için yaratılmış sesi ile çok güzel ve sade şekilde anlatıyor. Tebrikler.'},
    { review_owner:'Muhammet Yıldız', txt:'Hocam çok teşekkür ederim. Güzel bilgiler öğrendim. Kurstan iyi bir şekilde istifade ettim. Kursa kaydolan ve kaydolacak olan arkadaşlara tavsiyem çok çok uygulama yapmanız. Teşekkürler'},
    { review_owner:'Ferad Bekir', txt:'HERKEZE RAHATLIKLAN ONERE BILECEGIM BIR EGITIM!!!! SAKIN, NET, ANLATIM, NORMAL BIR KURSATA PAUSE YOKTU. BURDA ISTEDIGIN KADAR DURDUR BEYNINE KAZI DENE VE TEKRAR DEDE. BASARILAR. :)'},
    { review_owner:'Yunus Polatgil', txt:'Hocamıza teşekkür ederim, sıkılmadan izlediğim eğitimlerden birisi'},
    { review_owner:'Hulusi̇ Erdal', txt:'Bir konu başlığı altındaki uygulamaları anlattıktan sonra konuyu bitirirken son olarak o konu başlığını çalıştırmayı  yinelersek, hatırda daha kalıcı olur ve burayı nasıl başlatmıştık  gibi (herkes için geçerli değil tabi ki) akılda bir soru işareti kalmadan ilgili videoyu daha hızlı tamamlamış oluruz diye düşünüyorum.Anlatımınız çok akıcı. Bu sebeple bir defada çok sayıda videoyu sıkılmadan saatlerce izleyebiliyorum.Emeğiniz ve paylaşımınız için çok teşekkürler.'},
    { review_owner:'Onur Bıyık', txt:'Size sadece şunu diyorum: "Afgan Rasulov farkı!!"Eğer emin değilseniz YouTube üzerinden kendisinin videolarına bir göz atın derim ve bu kursu aldığınızda cidden sıfırdan güzel bir seviyeye geldiğinizi de göreceksiniz.'},
    { review_owner:'Fatih Bingül', txt:'kusursuz bir kurs Afgan Rasulov farkı'},
    { review_owner:'Volkan Şen', txt:'afgan bey gerçekten bu işin hakkını vererek yapıyor.'},
    { review_owner:'Serhat KAV', txt:'Kursa yeni başladım ve daha önce youtubeden zaten Afgan hocamı dinliyordum ve photoshopa başlamamın  tek sebebi Afgan hocamdır. Şuanda  yavaş yavaş ilerliyorum ve daha iyilerini yapacağıma inanıyorum  şimdiden teşekkürler.'},
    { review_owner:'Halil İbrahim Hazır', txt:'Gayet ayrıntılı anlatıyor. Muğlak bir nokta yok.'},
    { review_owner:'Selçuk Keskin', txt:'Yeni başlayanlar için en ideal ve tek kurs. Afgan beyin öğretme metodu çok mükemmel. Başkalarından da kurs aldım ama Afgan beyle yeniden doğdum adeta. Hiç bir şey bilmiyormuşum.  Teşekkür ederim, Afgan bey.'},
    { review_owner:'Hüseyin Yıldız', txt:'Afgan Rasulovun youtube üzerinde yayımladığı videoları takip eden biri olarak bu dersi çok büyük bir istekle aldım.Kesinlikle pişman olmayacağınız sonuna kadar sabırla izlenmesi ve uygulanması gereken bir ders.Teşekkürler.'},
    { review_owner:'Çayan Gündoğdu', txt:'Muhteşem bir kurs ve akıcı anlatım.Orta düzeyde bilgim vardı şimdi ise daha yüksek bir düzeyde çalışıyorum.Teşekkürler.'},
    { review_owner:'Mert Bolut', txt:'harika bir öğretici'},
    { review_owner:'Batuhan Altay', txt:'Anlatımı çok güzel ve sade. Bir şeyi yapmanın birden çok yolunu anlatıyor. Özet olarak gerizekalıya anlatsa anlar. İyi ki almışım'},
    { review_owner:'Servet Esat YILMAZ', txt:'anlaşılır tane tane iyi ya işte adsfasdfsad'},
    { review_owner:'Metin Özcan', txt:'gayet güzel sıkmadan detaylı anlatım'},
    { review_owner:'İbrahim KELEŞOĞLU', txt:'Gayet faydalı ve öğretici PhotoShop adına her şey var.Tavsiye ederim.'},
    { review_owner:'Adil Karadağ', txt:'çok süper anlatım'},
    { review_owner:'İsmail Oflas', txt:'proğramı öğretmeyi boşver adam kendi arayüzünüzü kendi kısayollarınızı kullanmadığınız menüleri kaldırmayı sık kullanılan menüleri renklendirip görmeyi daha kolaylaştırmasıve ayriyetten liste üzerinden ve kısayollardan panellere rahatlıkla ulaşabilmeyi adam bildiğin proğram öğretmeyi boşver adam proğramı daha nasıl rahat kullanırız diye bir çaba içerisinde helal olsun böyle eğitimciler varmı hala ne diyryim'},
    { review_owner:'Yucuklu Sumurta', txt:'memkun kalma garantili'},
    { review_owner:'Emin kağan yürüden', txt:'çok güzel,kolay anlatım....TEŞEKKÜRLER'},
    { review_owner:'Can Tombul', txt:'EVET GERÇEKTEN HARİK'},
    { review_owner:'Bezat', txt:'Parasını sonuna kadar hak eden bir insan. Hatta bu kadar ucuza bu eğitimi aldığıma utanıyorum.'},
    { review_owner:'Ferhat Yıldırım', txt:'basit anlaşılır'},
    { review_owner:'Arda Yılmaz', txt:'evet'},
    { review_owner:'Kadir Okan Morkoç', txt:'Afgan rasulovo tesekur ederim umarum youtube banner yapımınıda ogrenirim saolasın kral geri donus yaparsın umarum daha fazla video izlemedim hepsini izliyiceğim hepsini anlamaya calıosıcagım'},
    { review_owner:'Shadow', txt:'Daha önce farklı platformlarda da birçok eğitim videosu izledim, satın aldım fakat giriş seviyesinin biraz üzerinde photoshopu bilen birisi olarak bile kurstan muhteşem keyif aldım. Beni mest eden yanı açılan/gösterilen bir pencerenin içerisinde ne özellik varsa ne işe yaradığı anlatılmış ve nasıl uygulandığı da harika örneklerle anlatılmış. Bir kursun aslında en önemli yanı olan anlatımcının cümle kurması. Bu kursta eğitmen Türkçeye hakim diliyle o kadar harika anlatım sağlıyor ki kursun içerisinde akıp gidebiliyorsunuz ve soluksuz bir şekilde sona doğru geliyorsunuz. Kursa 3 akşam ayırdım ve %95ini bitirdim. Muhteşem şeyler öğrendiğimi düşünüyorum. Artık 2 şey benim açımdan kesin; Birincisi Photoshop benim için çocuk oyuncağı, ikincisi ise Afgan Rasulovun vereceği tüm kursları gözü kapalı satın alacağım (tabiki ilgi alanıma göre). After effects, Premier pro gibi diğer programlardan da bu şekilde Adan Zye bir kurs hazırlarsa bekliyor olacağım. Harika kurs için Teşekkürler Afgan Rasulov.+ See more'},
    { review_owner:'Koray Şimsek', txt:'cok faydalı bir kurs herkese tavsiye ederim'},
    { review_owner:'Anıl Başer', txt:'Kişisel gelişim için güzel bir adım.'},
    { review_owner:'Erkan KUZU', txt:'Harika bir anlatımdı, teşekkür ediyorum Afgan Rasulov...'},
    { review_owner:'Betül Gök', txt:'Bu kursun benim için çok faydalı olacağına inanıyorum.'},
    { review_owner:'Gürkan Tosun', txt:'bu kadar net ve güzel bir anlatımı yorumsuz bırakmak mümkün olmaz. yıllardan beri kendisini youtube kanalından takip ediyorum. bana photoshop u sevdiren adamdır kendisi. herşey için teşekkür ederim.'},
    { review_owner:'Betül Kırbağ', txt:'Anlatımı süper hiç sıkıcı değil bu eğitim 5 değil 10 yıldızı hak ediyor ?'},
    { review_owner:'Mehmet Akif ÖZTÜRK', txt:'Egzersizleri üç kez tekrar ederek pekiştiriyorum. Şimdiye kadar öğrendiklerime bile birçok şey yapabiliyorum. Afgan beyin diğer derslerini de bu yüzden hemen aldım. Çok güzel bol tekrarlı bol egzersizli ve egzersiz fotoğraflarının da paylaşılmış olmasıyla çok faydalı bir öğrenme süreci oluyor. Teşekkür ederim.'},
    { review_owner:'Ahmet Yurtsever', txt:'Gayet güzel ve avantajlı bir eğitim. tevsiye ederim'},
    { review_owner:'Ağabala', txt:'fotoğrafçılıkta çok yardımı dokundu çok sağolun'},
    { review_owner:'Serhat ALTUN', txt:'Kurs içeriği kolay anlaşılır,sade ve  ses kalitesi oldukça iyi.'},
    { review_owner:'Berkay Bektaş', txt:'evet ilerleyen zamanlarda da göreceğiz'},
    { review_owner:'Serkan Kalmaz', txt:'Kesinlikle Doğru ve mükemmel tercih. Detaylı anlatım , akıcı konuşmasıyla profesyonelliğe hızlı bir adım atıyorum.'},
    { review_owner:'Muhammed Tüzün', txt:'Her şey açık ve net teşekkürler Afgan Rasulov.'},
    { review_owner:'Ahmet Polat', txt:'güzel  iyi'},
    { review_owner:'Ümit Koşaner', txt:'Amatör bir fotoğrafçı olarak öğrenmek istediğim Photoshop programını çok detaylı bir şekilde Afgan bey’in eğitimiyle öğrendim...'},
    { review_owner:'Gökhan Sağlık', txt:'Son derece akıcı ve anlaşılır bir anlatım.'},
    { review_owner:'Barış Bilgin', txt:'Şuan elimde aktif olarak kullandığım 2 adet kurs var fakat afgan beyi tebrik ederim'},
    { review_owner:'Bülent Demir', txt:'Şimdiye kadar oldukça başarılı bir anlatım ve sürükleyici bir işleyiş söz konusu'},
    { review_owner:'Adnan', txt:'Herkese tavsiye ediyorum.'},
    { review_owner:'Abdukerim Abduselam', txt:'güzel eğitici'},
    { review_owner:'Rose_leslie', txt:'SON DERECE  ANLASILABILIR BIR IFADE ILE DETAYLI IFADE EDILEN BIR KURS OLMUS . TESEKKURLER'},
    { review_owner:'Mutlu Erdur', txt:'Gayet açıklayıcı eğitim olmuş. Teşekkürler'},
    { review_owner:'Bilal Salar', txt:'şimdilik güzel gidiyor'},
    { review_owner:'Murat Keles', txt:'Afgan Rasulov anlatımını çok beğeniyorum. Eğitimleri benim için çok verimli geçiyor.'},
    { review_owner:'Hakan Pa.', txt:'Eğitim çok güzel.'},
    { review_owner:'Ubeydullah Karabacak', txt:'çok iyi anlatıyor diğer anlatıcılar gibi sıkıcı ve baygın bir anlatım tarzı yok dikkat çeken bir anlatım ile çok zevk alarak derslerini izliyorum'},
    { review_owner:'Süleyman Altınkaya', txt:'Adan Zye cümlesi bu kurs için tamamen doğru'},
    { review_owner:'Murat Baloğlu', txt:'Afgan Beyin bilgi birikimi ve akıcı anlatımı, kursa merakla ve keyifle devam etmenizi sağlıyor. Youtube kanalındaki ücretsiz videolarını izlemiştim ve ondan sonra bu seti satın almaya karar verdim. İyi ki de satın almışım. Ödediğiniz paranın her kuruşunu hak eden bir anlatım-öğretim tarzı ve emeği var. After Effects ve Premiere için de full bir eğitim seti hazırlamasını dört gözle bekliyorum.'},
    { review_owner:'Murat Sezgin', txt:'Kesinlikle :-)'},
    { review_owner:'Gökhan Fışıloğlu', txt:'Hiç photoshop ile ilgili bilgisi olmayan bir kişi için temelden başlanması açısından uygun. Fakat temel ve orta düzey açısından sıkıcı olma durumu doğuyor. Ama sonuç olarak herkesin öğrenmesi için yapılan bir eğitim olduğu için baştaki kısımlar mazur görülmeli.'},
    { review_owner:'Ziya Kadir Şakak', txt:'İLK DEFA DUYDUM ANCAK ALMAYI DÜŞÜNÜYORUM SİZİN ANLATIMINIZDAN SONRA'},
    { review_owner:'Sefa Çam', txt:'iyiymiş'},
    { review_owner:'Mahmut Serdar Kaya', txt:'çok sade anlatım sayesinde herkes anlayabilir.'},
    { review_owner:'Mustafa', txt:'hiç bilmeyen birinin 0 başlayarak yapabileceğime baya emin oldum photoshop ile alakalı tek bildiğim görüntü boyutu ayarlama'},
    { review_owner:'Sadettin Özer', txt:'Gayet güzel, anlaşılır ve adım adım uygulamalı. Harika. Tavsiye ederim.'},
    { review_owner:'Oğuzhan AKTAŞ', txt:'SORUNUM VAR'},
    { review_owner:'Çiğdem Erkin', txt:'Çok memnun kaldım'},
    { review_owner:'Akin Pangal', txt:'Anlatım gayet açık ve anlaşılır şimdilik iyi gidiyor bakalım'},
    { review_owner:'Mehmet Altunçay', txt:'Photoshop programına ilk merak sardığım 2013 yılında youtube da denk gelmiştim  videolara bir kaç ay geçtikten sonra fark ettim ki ondan daha iyi içerikler sunan Türk yoktu ve şuan yıllar sonra halen grafikle ilgili bir sorun yaşadığımda onun kanalında buluyordum cevapları, Bu yıl photoshop üzerinde başarılı çalışmalar yaptım ve iş teklifi aldım ve kendimi daha fazla geliştirmek için yine aynı kişiye başvurdum . Teşekkürler Afgan Rasulov..'},
    { review_owner:'Hacibekir Yalçın', txt:'Afgan Rasulov=Kalite'},
    { review_owner:'Kaya Kologlu', txt:'Harika bir anlatım basit ama çok etkili ??'},
    { review_owner:'Oğulcan Kurtuluş', txt:'şimdiden çok şey ögrendim'},
    { review_owner:'Eda Nur Harputlu', txt:'evet teşekkür ederim.'},
    { review_owner:'Akdayi81', txt:'Eğiticinin anlatımından dolayı afkan gerçekten çok güzel ders anlatıyor'},
    { review_owner:'Murat Karakuş', txt:'Şimdilik bir sorun yok kursa devam'},
    { review_owner:'Yetkin', txt:'Gerçekten harika bir eğitim, Afgan Beyin çok güzel bir anlatımı var bu kurs benim için çok yararlı oldu kendisine teşekkür ediyorum. Emeğinize sağlık.'},
    { review_owner:'Hülya Hayta', txt:'Şimdiye kadar olan süreçte birçok faydalı bilgi edindim teşekkürler'},
    { review_owner:'Gökhan Dayıoğlu', txt:'evet'},
    { review_owner:'Ebutalha Camadan', txt:'Oldukça doğru bir eşleşmeydi.'},
    { review_owner:'gürkan kızıldağ', txt:'Adam harika'},
    { review_owner:'Bahar Şamlı', txt:'Harika ve kesinlikle beklentilerimin üstündeydi.'},
    { review_owner:'Sevgi Karakaş', txt:'çok yararlanıyorum.'},
    { review_owner:'Bumin Kaan Yanık', txt:'kesinlikle benim için mükemmel bir deneyim oldu'},
    { review_owner:'Cem şahin', txt:'Güzelll'},
    { review_owner:'Cenan', txt:'ANLATIŞI SÜPERR=)'},
    { review_owner:'Volkan Usta', txt:'Gayet başarılı bir şekilde devam ediyor eğitimler.Anlatım tarzı gerçekten çok iyi sade ve yalın. Teşekkürler'},
    { review_owner:'Eminecimnoluyo', txt:'şimdlik iyi gidiyor'},
    { review_owner:'Mustafa ANLAYAN', txt:'HARİKA'},
    { review_owner:'Şevval Özer', txt:'kesinlikle!'},
    { review_owner:'Serhat Bozkurt', txt:'Çok eğlenceli içten bir kurs'},
    { review_owner:'Mert Ali Dalkır', txt:'güzeldi'},
    { review_owner:'Ahmet Yahya Özden', txt:'Afgan Hocam kesinlikle işinin ehli birisi. Güzel ve detaylı anlatımı insanda çok kalıcı ve güzel etkiler bırakıyor'},
    { review_owner:'Tuğba Kobal Yılmaz', txt:'tesekkür ederim size. inşallah öğreneceğim sayenizde :)'},
    { review_owner:'Abdullah Pehlivan', txt:'Yetkin anlatımı güzel'},
    { review_owner:'Atakan Barış', txt:'Sıfırdan başlayanlar için güzel bir eğitim seti olmuş. Gelişmiş özelliklerin kullanımı için hazırlanan videoları izleyince tekrar değerlendireceğim.'},
    { review_owner:'Bülent Erol', txt:'Güzel Türkçesi ve anlaşılabilir anlatımıyla büyük fayda sağlıyor.Bana uygun bir uygulama.Başarılar dost selamlar...'},
    { review_owner:'Saliha Tülin Türk', txt:'Kesinlikle pişman olunmayacak kurs programı'},
    { review_owner:'Burak', txt:'teşekkürler'},
    { review_owner:'Murat unal', txt:'Anlatım dili güzel, sıkılmadan öğreniyorsunuz.'},
    { review_owner:'Zet Ömer BOZKURT', txt:'iyi ilerliyor'},
    { review_owner:'Halil İbrahim sağman', txt:'Kursu yeni satın aldım, sonucunun başarılı olacağından şüphem yok, hocamın sayesinde inşallah güzel işler başaracağız..'},
    { review_owner:'İsmail', txt:'YouTubedan buraya kadar gelen süreç için.'},
    { review_owner:'Ege Erol', txt:'EVET'},
    { review_owner:'mahmuthan orun', txt:'all good'},
    { review_owner:'Aksoy', txt:'Her detayiyla anlatilmasi harika gercekten cok tesekkur ederim :D'},
    { review_owner:'Nurullah Aydın', txt:'Tek kelime ile harika. Bilgi donanım ve anlatım tarzı yönünden çok iyi.'},
    { review_owner:'Novruz Ahmadov', txt:'BELƏ GÖZƏL BİR TƏŞƏBBÜSÜN ÖZ HƏMVƏTƏNLİM TƏRƏFİNDƏN HƏYATA KEÇİRİLMƏSİ ÇOX GÖZƏLDİR.'},
    { review_owner:'Metincan6161', txt:'Afgan Abi 2.Eğitimide Satın Aldım. Senin Sayende Youtubeda Artık Güzel Ve Kaliteli İçerikler Sunup Herkeze Sunabiliceğiz. Herşey İçin Teşekkür Ederim. https://www.youtube.com/channel/UCGkxXUkk1cQL6d5pdKO95IwKanalım Bu Afgan Abi İnşallah Güzel Yerlere Geliceğim. Sayende Tekrardan Teşekkür Ederim.'},
    { review_owner:'Abdullah Pakoğlu', txt:'kolay bir şekilde ulaşabileceğim kaynak olacak'},
    { review_owner:'Arzu Seki̇n', txt:'Kendisinin emeğine sağlık. Zaten Youtube kanalından da takip ediyorum. İşini o kadar seviyor ki, bunu eğitimlerde de çok iyi hissettiriyor. Kurslara gittiğim halde sayesin de hem Photoshop programını hem de Premiere Pro programını buradan öğrendim. Anlatımı ve atış noktaları çok iyi.. Kısacası çok çok iyi. Devamını dilerim. Özellikle Premiere Pro detaylı anlatım eğitimi verirse çok sevinirim.tekrar tekrar teşekkür ederim.Arzu Sekin+ See more'},
    { review_owner:'İsmail Uslu', txt:'Deneyiminizi bizimle paylaştığınız için teşekkürler.Lütfen daha çok örnek çalışma yükleyin. Günlük çekilen bir fotoğraf üzerinde neler yapabiliriz , bu konu hakkındaki yaratıcılığınızı bizimle paylaşırsanız da sevinirim.'},
    { review_owner:'Sinasi ARSLAN', txt:'Photoshop konusunda herzaman takip ettiğim bir eğitmen. Bu dersi de çok faydalı buldum. Genel tekrarı güzel bir uygulama ile de pekiştirmiş. Bir manzara fotoğrafını düzenlemekle ilgili de detaylı bir örnek çekerek derse eklemesini de umut ediyorum. Teşekkürler emeğine sağlık Afgan Hocam.'},
    { review_owner:'Onur Baykan', txt:'Artık fotoğraf düzenlemek ve arşivlemek çok daha kolay hale geldi. Anlatımı sıkıcı değil ve eğitimin her anı dolu dolu geçiyor.Teşekkürler'},
    { review_owner:'İsrafi̇l Serdar Gültepe', txt:'İnce ayrıntıları öğrendim. Giriş seviyesinde bir öğrenciyken şuan orta seviyenin az daha ilerisinde bir öğrenciyim. Kendime hiçbir zaman da profesyonel demeyeceğim çünkü zaman ilerledikçe yenilikler olacaktır yeniliklere açık olup kendimize bu kadar yeterlidir demeden sürekli öğrenme çabası içerisinde olmalıyız düşüncesini aşıladım. Bu kurs ile ilgili önerim sadece şu olabilir bu kursu almış bir öğrenci olaraktan, ayrı bir bölüm daha koyulup kursun içeriğine bonus olarak bu bölümede egzersiz bölümü denerek egzersiz sayısı biraz daha arttırılabilir daha detaylı daha fazla örnekle kursun içerisindeki eğitimlere destek sağlanabilir görüşündeyim. Bunların dışında kurs gerek hobi gerekse fotoğrafçılığı meslek edinmek isteyenler için kaçırılmaz fırsat gerekli çoğu bilgiyi içinde barındırmaktadır.+ See more'},
    { review_owner:'Yunus Sarıusta', txt:'Egzersizler biraz az; bununla birlikte çok zor teknikleri bile iyi anlatmış. Anlatım biraz tek düze ses tonuyla gitmiş ancak o kadar kusuru olur. Eninde sonunda bir online kurs bu. Nesif bir klavuz olduğunu düşünüyorum.'},
    { review_owner:'Sefa Yurtsever', txt:'Kesinlikle'},
    { review_owner:'Zafer Payçu', txt:'Afgan Beyi youtubea ilk video yüklemesinden beridir (7yıldır) takip ediyorum. Kendisinin neredeyse tüm kurslarını satın aldım. Sayesinde bu mesleğe adım atıp, kariyerimde yükseliyorum. Kendisine ne kadar teşekkür etsem azdır. Birçok yararlı bilgiyi en sade, yalın anlatımıyla bizlere sunuyor. Kendisinin birebir kullandığı yöntemleri açık açık anlatıp, tüm sorulara en içtenlikle cevap veriyor. Bu kursta en çok profesyonel rötuş tekniğini beğendim. Acılar; biraz daha fazla uygulamalı ve ileri seviye kesime hitaben (Yeni başlayan ve orta seviyeye değil) içerikler yaparsanız çok daha mutlu oluruz. Herşey için teşekkürler, takipteyiz.+ See more'},
    { review_owner:'Mustafa Kemal', txt:'Evet Doğru bir Karar verdiğime inanıyorumDers ilerledikce heycanla öğreniyorumtatlı bir yorgunlukla bitti eğitim,birşeyler katı bana'},
    { review_owner:'Remzi Yılmaz', txt:'harika bilgiler teşekkürler :)'},
    { review_owner:'Sevi̇n Çeti̇ntaş', txt:'Photoshop kullanır hale geldim. Daha profesyönel öğrenmek isterim. Bilen  değil yapabilen olmak istiyorum . Yüreğine sağlık hocam .'},
    { review_owner:'Sinan Koyuncu', txt:'Emeğinize sağlık. İlk başlarda aynı şeylerin çok fazla tekrar edildiğini düşünsem de ileriki dönemlerde bunun faydasını gördüm. Faydalı bir kurs, çok teşekkürler!'},
    { review_owner:'Güven ALTAY', txt:'Teşekkürler amatör olarak fotoğraf çekimi ve photoshop kullanıyorum eğitimleriniz sayesinde güzel bir hobi yakalamış oldum.'},
    { review_owner:'Recai Sönmez', txt:'Anlatım çok güzel açıklayıcı birçok adobe alanındada güzel eğitimler istiyorum çok kısa zamanda  kolay bir şekilde kavrıyorum teşekkürler Afgan Bey.'},
    { review_owner:'Aykut kaysı', txt:'afgan hocam harikasınız.istediğim tüm dersler neredeyse eğitim videolarınızda vardı.artık sizin sayenizde istediğim shopları yapabiliyorum :)'},
    { review_owner:'Enver Murat', txt:'bu kursta merak edipte öğrenilemeyecek hiçbir şey yokartık photoshopa karşı ön yargılarım tamamen yıkıldı diyebilirim, bu kurs bana disiplinli bir şekilde photoshopa yaklaşmayı öğretti, şu anda yapabildiklerim beni de şaşırtmaya başladı diyebilirim ama her işte olduğu gibi bununda ilacı pratik yapmaktan geçiyor, teşekkürler Afgan Rasulov.'},
    { review_owner:'Mustafa dönmez', txt:'Benim için çok faydalı bir eğitim,photoshop ta eksik olan bilgilerimi tamamlıyor'},
    { review_owner:'Salih Bestami ÖĞRETİM', txt:'belirli saatlerde canlı soru cevap kısmı olsa daha iyi olabilir'},
    { review_owner:'Sedat', txt:'Hocamız Sağolsun Çok Güzel Anlatıyor.Faydalı Ve Akıcı Bir Anlatım Var.'},
    { review_owner:'Nafibostanbas', txt:'Anlatımı olsun kullanımı olsun gayet güzel. Teşekkürler'},
    { review_owner:'SAMET BALCI', txt:'evet'},
    { review_owner:'Sezin Çobanoğlu', txt:'Emeğinize sağlık. Çok teşekkürler...'},
    { review_owner:'naci çağlar dalak', txt:'Bu eğitim seti gerçekten hiç bilmeyen ve sıfırdan öğrenmek isteyen kişilere yol göstermek ve iyi bir şekilde kavramalarını sağlamak için hazırlanmış bir eğitim seti. Tavsiyem, daha önce biraz photoshop ile haşır neşir olan kişilerin bu eğitimi almalarının bir faydası olmayacağıdır. Sıfırdan başlayanlara ise gerçekten faydalı ve iyi bir kılavuz olacaktır. Emeğiniz için teşekkürler.'},
    { review_owner:'Yusuf Bolat', txt:'Çok harika bir eğitmen severek takip ediyorum,Youtubedan bile umarım hayatında iyi işler yapar.Eğitimi satın aldık çok iyi eğitmen.'},
    { review_owner:'Elmaddin Karimov', txt:'So far so good'},
    { review_owner:'Bayram Özer', txt:'kursa yeni başladım. başlangıç olarak hem anlatım olsun hemde farklı teknik denemeleri  güzel yeni olduğum için burda kesin konuşmak erken ama tabi biz ne kadarını dinleriz o bize kalmış yapılan teknikler tekrar edilmezse ne kadar güzel anlatılırsa anlatılsın birşey öğrenemeyiz.TEKRAR ETMEK ÖNEMLİ'},
    { review_owner:'Sedat Polat', txt:'evet şuana kadar iyi buldum'},
    { review_owner:'Bilgehan Eroğlu', txt:'Kendisini uzun süredir youtube üzerinden de takip ediyordum ve Udemyde kurs verdiğini görür görmez tereddüt etmeden aldım,aldığıma da fazlasıyla mutluyum.Bu uğraşı olan dostlarıma kesinlikle öneririm,hem işinin ehli ve samimi bir insan hem de yaptığı işte çok iyi,açıklayıcı anlatımıyla beraber muazzam bir kurs olmuş çok beğendim iyi çalışmalar. :)'},
    { review_owner:'Birgül Ivecan', txt:'Teşekkürler'},
    { review_owner:'Ajlan Uçar', txt:'Teşekkür ederim'},
    { review_owner:'Ahmet Köse', txt:'Afgan rasülov  müthiş bir insan. Kendisine teşekkür ediyorum emeğine sağlık YouTube’dan takip ediyorum kösegraf TV ??'},
    { review_owner:'Emice A', txt:'Afgan Rasulovu youtube de takip ediyordum. Gayet güzel bir anlatımı var. Daha derli toplu bir eğitim gibi duruyor şimdilik.'},
    { review_owner:'Sedat Aydogan', txt:'Detaylı ve açıklayıcı bir kurs'},
    { review_owner:'Abdulrahim Şahinler', txt:'gayet başarılı'},
    { review_owner:'Ibrahim Karaaslan', txt:'harika....'},
    { review_owner:'Mustafa', txt:'harika'},
    { review_owner:'İbrahim Efe Memişoğulları', txt:'sıkılmadan eğlenceli bir şekilde bu deneyimi yaşattığın için teşşekür ederiz.'},
    { review_owner:'Uğur Sezer', txt:'Bu kursun çok faydalı olacağını düşünüyorum ve bu konuda hiç şüphem yok Afgan a güveniyorum. Ayrıca şu ana kadar açık ve anlaşılır konuşması çok hoşuma gitti. Kurs sonunu hevesle bekliyorum.'},
    { review_owner:'Yüksel SARAÇ', txt:'Anlatım çok akıcı, düzgün bir Türkçe videoların devamını sabırsızlıkla izleyeceğim.'},
    { review_owner:'Neriman Alpagut', txt:'Şimdiden çok beğendim.'},
    { review_owner:'Volkan Şahinler', txt:'Harika....hoca cok detaylı anlatıyor...'},
    { review_owner:'Einsteinz', txt:'Eğitmenin çok sade güzel bir dili var.'},
    { review_owner:'Özkan Özertekin', txt:'Başka kaynağa gerek yok en iyi kurs afgan hocanın kursu'},
    { review_owner:'Fatma Demir', txt:'sanırım'},
    { review_owner:'Gavur Hoca', txt:'crystal clear'},
    { review_owner:'S. Ender ÇUBUKÇU', txt:'Akıcı ve anlaşılır.'},
    { review_owner:'Erhan SARISARAY', txt:'Afgan beyi youtubede tanımıyan yok gibi .Verdiği eğitim çok başarılı.Tereddüt etmeden bu eğitimi alabilirsiniz.Parasını sonuna kadar hak ediyor.'},
    { review_owner:'Emirhan', txt:'Valla Çok Güzel Anlatımı Var. Bilmediğim Konularıda Öğrendim.Devamlarını Çok Merak Ediyorum.. :)'},
    { review_owner:'Yusuf Bahri YILMAZ', txt:'Daha yeni başladım ve gayet memnunum zaten Afgan abiyi youtubeden de takip ediyordum'},
    { review_owner:'Enes DEĞİRMENCİ', txt:'Güzel başlangıç'},
    { review_owner:'Kerim Tellioğlu', txt:'en çok öğrenmek istedğim programlardan biriydi ve galiba doğru karar vermişim.'},
    { review_owner:'Mustafa Memiş', txt:'anlatim gayet seri ve açık'},
    { review_owner:'Yılmaz Tokatlı', txt:'Gayet akıcı ve net bir anlatım mevcut, tavsiye ederim. :)'},
    { review_owner:'Merih Salmaz', txt:'Anlatım sade,akıcı ve anlaşılır.'},
    { review_owner:'Burhan', txt:'evet doğru adresteyim.afgan rasulovun youtube videolarıda harika.tşk ediyorum.faydalı bir eğitim olacağına inanıyorum'},
    { review_owner:'Dilek', txt:'Henüz derslere başlamadığımız için, yorum yapamayacağım'},
    { review_owner:'Ahmet Aslan', txt:'Çok verimli'},
    { review_owner:'Nurten Özan', txt:'Afgan Rasulov un pek çok eğitim videosunu daha önce izlemiştim, ve işime yarayan çok şey öğrendim. Şimdi ise elimin altında sürekli bulunacak olan ve unuttuğumda geriye dönüp bakabileceğim bir eğitim setim var. Teşekkürler Afgan Rasulov.'},
    { review_owner:'Bülent Karagözcük', txt:'kurs içindeki bölümlere kolay ulaşılamıyor diğer yanları çok başarılı profesyonelce tebrikler'},
    { review_owner:'Ertuğrul Evli̇yaoğlu', txt:'Afgan Rasulov öncelikle insanlığından dolayı çok teşekkür ederim eğitimlerini alın almayın ne zaman birşeyler danışsanız çok hızlı bir şekilde yardımcı oluyor , ben birşeyler öğrenmek istedim hemen gerekli resimleri png formatında gönder  nasıl yapacağın hakkında video çekip eğitime ekliyeyim dedi .      Var mı böyle yardımcı olan Türkiye Cumhuriyetinde ? Afgan hocam sen Allahın bir lutfusun  .... Tekrar Tekrar çok teşekkür ediyorum eğitimlerini gözü kapalı alın şiddetle tavsiye ediyorum eğitimleri aldıktan sonra farkı göreceksiniz ve Adamın dibi bir hocayla tanışmış olacaksınız .+ See more'},
    { review_owner:'Huseyn Gurbanov', txt:'Çox bəyəndim.'},
    { review_owner:'Özlem aydın', txt:'İyiydi'},
    { review_owner:'Şeydanur Işbilir', txt:'Oldukça iyi'},
    { review_owner:'Tahsin Barış', txt:'evet'},
    { review_owner:'Osman Furkan Esgidir', txt:'Çok memnunum...'},
    { review_owner:'Furkan S.', txt:'Afgan Hocadan birçok şey öğrendim Photoshop u açmayı dahi bilmiyordum. Öğrenmeye devam ediyorum iyiki varsınız.'},
    { review_owner:'Bilal Gökçe', txt:'Afgan Rasulov bir markadır.'},
    { review_owner:'İhsan Uğur Işık', txt:'kesinlikle'},
    { review_owner:'Barış Balcı', txt:'İnşallah bu eğitim seti sürekli güncel olur. Yeni videolar eğitimler yüklenmeye devam eder. Minimum 50 saatlik bir kurs olmasını beklerim. Yemekten , yoldan kısıp 25 lira para verdik. İnşallah faydalı olur.'},
    { review_owner:'Kemal Uysal', txt:'evet'},
    { review_owner:'Rumeysa Keleş', txt:'Çok yalın net bir şekilde anlatılmış harika... emeğinize sağlık?'},
    { review_owner:'Fikrolog S', txt:'Şimdilik güzel gidiyor'},
    { review_owner:'Sümeyye Arslan', txt:'Herşey çok anlaşılır, ve çok zevkli. Teşekkürler..'},
    { review_owner:'Bülent ÇELİKDEMİR', txt:'Afgan Rasulov abimin eğitimlerini zaten takip ediyordum fakat şimdi daha profesyonel olarak almaya karar verdiğimden eğitime başladım ve gayet memnunum'},
    { review_owner:'Ali-Ruso Mamedov-Musayev', txt:'cox gozel kursdu'}
]